# Generated by Django 3.2.19 on 2023-06-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230608_1546'),
        ('recipes', '0004_auto_20230516_1003'),
    ]

    operations = [
    ]
