# Generated by Django 3.2.19 on 2023-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_0002_auto_20230608_1546_0005_auto_20230516_1003'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscribing'),
        ),
    ]
